### ISSUE TITLE
gtctl v0.1.0 milestone

### ISSUE THREAD

**Issue by zyy17** [GreptimeTeam/gtctl#90]
## Overview

To catch up on the v0.4 release of GreptimeDB, the gtctl project decided to release v0.1.0 in **mid-August**. The main features of v0.1.0 gtctl are as follows: 

1. Support the complete deployment of GreptimeDB on K8s;

2. Support the complete deployment of GreptimeDB on the bare metal scenario (mainly for development purposes);

3. Unify the CLI UI on different deployment scenarios;

We hope v0.1.0 gtctl can help most GreptimeDB users to deploy the GreptimeDB as efficiently as possible. We will bring more great features at v0.2.0.

If you're interested in the project, you can check more details by [Development Kanban](https://github.com/orgs/GreptimeTeam/projects/32/views/1) and [Milestone](https://github.com/GreptimeTeam/gtctl/milestone/1). **Just feel free to ask us any questions**(GitHub issues or [Slack](https://greptime.com/slack))😊! 

When we release v0.1.0, we will **switch to the `main` branch** and use it as the default branch.

### Features

- [x] https://github.com/GreptimeTeam/gtctl/issues/91
- [x] https://github.com/GreptimeTeam/gtctl/issues/88
- [x] https://github.com/GreptimeTeam/gtctl/issues/80
- [x] https://github.com/GreptimeTeam/gtctl/issues/5
- [x] https://github.com/GreptimeTeam/gtctl/issues/3
- [x] https://github.com/GreptimeTeam/gtctl/issues/96

### Tests

- [ ] https://github.com/GreptimeTeam/gtctl/issues/94

### CI

- [x] https://github.com/GreptimeTeam/gtctl/issues/83
- [x] https://github.com/GreptimeTeam/gtctl/issues/93

### Releasing

- [x] https://github.com/GreptimeTeam/gtctl/issues/97
- [x] https://github.com/GreptimeTeam/gtctl/issues/92

### Documentation

- [ ] https://github.com/GreptimeTeam/gtctl/issues/95

**Comment by zyy17** [comment]
In fact, due to my limited energy, the publishing process did not go as smoothly as I expected. Most of the issues related to the release are finished except for some tests and refactoring.

I will reschedule the issues and make a new release plan. According to my rough estimate, this release will be completed in May or June.
